# Script to create COE67_312_Model_Training.ipynb
import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🥭 COE67-312 Mini-Project: Mangosteen Ripeness Classification\n",
    "## Phase 2: Model Engineering, Quantization & Edge Deployment\n",
    "\n",
    "This notebook covers the complete Phase 2 workflow according to the course rubric:\n",
    "1. **Load and Augment Data** from Google Drive / Local dataset (`train`, `val`, `test`)\n",
    "2. **Handle Class Imbalance** (`unripe`: 104, `ripe`: 47, `overripe`: 19)\n",
    "3. **Design Lightweight CNN Architecture** ($\le 100,000$ parameters)\n",
    "4. **Train and Validate** aiming for Validation Accuracy $\ge 88\\%$\n",
    "5. **Full Integer (int8) Quantization** using TensorFlow Lite with minimal accuracy drop ($< 2\\%$)\n",
    "6. **Evaluate Test Set & Confusion Matrix**\n",
    "7. **Export `model_data.h`** (C byte array) ready to flash onto the ESP32-S3 (LilyGo T-SIMCAM)!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 1: Setup Environment & Mount Google Drive"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import shutil\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import tensorflow as tf\n",
    "from tensorflow import keras\n",
    "from tensorflow.keras import layers\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "from sklearn.metrics import classification_report, confusion_matrix\n",
    "\n",
    "print(f\"TensorFlow Version: {tf.__version__}\")\n",
    "print(f\"GPU Available: {len(tf.config.list_physical_devices('GPU')) > 0}\")\n",
    "\n",
    "# Mount Drive if running on Google Colab\n",
    "try:\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive')\n",
    "    print(\"Mounted Google Drive successfully.\")\n",
    "except Exception as e:\n",
    "    print(\"Running locally or Google Drive already mounted.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 2: Configure Paths & Verify Dataset Structure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Candidate dataset paths (Colab Drive & Local)\n",
    "possible_paths = [\n",
    "    '/content/drive/MyDrive/MiniProject/mangosteen_dataset',\n",
    "    '/content/drive/MyDrive/COE67-312/mangosteen_dataset',\n",
    "    'C:/AlahiMangosteen/Dataset/MiniProject/mangosteen_dataset',\n",
    "    './Dataset/MiniProject/mangosteen_dataset'\n",
    "]\n",
    "\n",
    "DATASET_DIR = None\n",
    "for p in possible_paths:\n",
    "    if os.path.exists(p):\n",
    "        DATASET_DIR = Path(p)\n",
    "        break\n",
    "\n",
    "if DATASET_DIR is None:\n",
    "    raise FileNotFoundError(\"Cannot find mangosteen_dataset directory. Please verify your Google Drive path.\")\n",
    "\n",
    "print(f\"Using Dataset Path: {DATASET_DIR}\")\n",
    "\n",
    "CLASSES = ['unripe', 'ripe', 'overripe']\n",
    "IMG_SIZE = (96, 96)\n",
    "BATCH_SIZE = 16\n",
    "SEED = 42\n",
    "\n",
    "# Verify counts\n",
    "for split in ['train', 'val', 'test']:\n",
    "    counts = {cls: len(list((DATASET_DIR / split / cls).glob('*.*'))) for cls in CLASSES}\n",
    "    print(f\"{split.upper():5s} set -> {counts} (Total: {sum(counts.values())})\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 3: Load Datasets and Calculate Class Weights (Handling Imbalance)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load Train, Val, and Test datasets\n",
    "train_ds = keras.utils.image_dataset_from_directory(\n",
    "    DATASET_DIR / 'train',\n",
    "    labels='inferred',\n",
    "    label_mode='categorical',\n",
    "    class_names=CLASSES,\n",
    "    image_size=IMG_SIZE,\n",
    "    batch_size=BATCH_SIZE,\n",
    "    shuffle=True,\n",
    "    seed=SEED\n",
    ")\n",
    "\n",
    "val_ds = keras.utils.image_dataset_from_directory(\n",
    "    DATASET_DIR / 'val',\n",
    "    labels='inferred',\n",
    "    label_mode='categorical',\n",
    "    class_names=CLASSES,\n",
    "    image_size=IMG_SIZE,\n",
    "    batch_size=BATCH_SIZE,\n",
    "    shuffle=False\n",
    ")\n",
    "\n",
    "test_ds = keras.utils.image_dataset_from_directory(\n",
    "    DATASET_DIR / 'test',\n",
    "    labels='inferred',\n",
    "    label_mode='categorical',\n",
    "    class_names=CLASSES,\n",
    "    image_size=IMG_SIZE,\n",
    "    batch_size=BATCH_SIZE,\n",
    "    shuffle=False\n",
    ")\n",
    "\n",
    "# Calculate class weights to handle imbalance (overripe has fewer samples)\n",
    "train_labels = []\n",
    "for _, y in train_ds:\n",
    "    train_labels.extend(np.argmax(y.numpy(), axis=1))\n",
    "train_labels = np.array(train_labels)\n",
    "\n",
    "class_weights_arr = compute_class_weight(\n",
    "    class_weight='balanced',\n",
    "    classes=np.arange(len(CLASSES)),\n",
    "    y=train_labels\n",
    ")\n",
    "class_weight_dict = {i: float(class_weights_arr[i]) for i in range(len(CLASSES))}\n",
    "print(\"Class Weights for balanced training:\", class_weight_dict)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 4: Data Augmentation & CNN Model Architecture (<= 100k Parameters)\n",
    "\n",
    "To comply with the assignment rules:\n",
    "- Total parameters must be **under 100,000**.\n",
    "- Use Conv2D + BatchNormalization + ReLU + GlobalAveragePooling2D.\n",
    "- GlobalAveragePooling2D drastically reduces memory footprint and inference latency on ESP32-S3."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_augmentation = keras.Sequential([\n",
    "    layers.RandomFlip(\"horizontal_and_vertical\"),\n",
    "    layers.RandomRotation(0.2),\n",
    "    layers.RandomZoom(0.15),\n",
    "    layers.RandomContrast(0.15),\n",
    "    layers.RandomBrightness(0.15)\n",
    "], name=\"data_augmentation\")\n",
    "\n",
    "def create_lightweight_cnn():\n",
    "    inputs = keras.Input(shape=(96, 96, 3), name=\"input_image\")\n",
    "    \n",
    "    x = data_augmentation(inputs)\n",
    "    x = layers.Rescaling(1.0 / 255.0)(x)\n",
    "    \n",
    "    # Block 1 (96x96 -> 48x48)\n",
    "    x = layers.Conv2D(16, (3, 3), padding='same', use_bias=False)(x)\n",
    "    x = layers.BatchNormalization()(x)\n",
    "    x = layers.ReLU()(x)\n",
    "    x = layers.MaxPooling2D((2, 2))(x)\n",
    "    \n",
    "    # Block 2 (48x48 -> 24x24)\n",
    "    x = layers.Conv2D(32, (3, 3), padding='same', use_bias=False)(x)\n",
    "    x = layers.BatchNormalization()(x)\n",
    "    x = layers.ReLU()(x)\n",
    "    x = layers.MaxPooling2D((2, 2))(x)\n",
    "    \n",
    "    # Block 3 (24x24 -> 12x12)\n",
    "    x = layers.Conv2D(48, (3, 3), padding='same', use_bias=False)(x)\n",
    "    x = layers.BatchNormalization()(x)\n",
    "    x = layers.ReLU()(x)\n",
    "    x = layers.MaxPooling2D((2, 2))(x)\n",
    "    \n",
    "    # Block 4 (12x12 -> 6x6)\n",
    "    x = layers.Conv2D(64, (3, 3), padding='same', use_bias=False)(x)\n",
    "    x = layers.BatchNormalization()(x)\n",
    "    x = layers.ReLU()(x)\n",
    "    x = layers.MaxPooling2D((2, 2))(x)\n",
    "    \n",
    "    # Classifier Head\n",
    "    x = layers.GlobalAveragePooling2D()(x)\n",
    "    x = layers.Dropout(0.3)(x)\n",
    "    x = layers.Dense(32, activation='relu')(x)\n",
    "    outputs = layers.Dense(3, activation='softmax', name=\"prediction\")(x)\n",
    "    \n",
    "    model = keras.Model(inputs=inputs, outputs=outputs, name=\"Mangosteen_Edge_CNN\")\n",
    "    return model\n",
    "\n",
    "model = create_lightweight_cnn()\n",
    "model.summary()\n",
    "\n",
    "param_count = model.count_params()\n",
    "print(f\"\\nTotal Parameters: {param_count:,}\")\n",
    "if param_count <= 100000:\n",
    "    print(\" PASS: Model parameters <= 100,000 as required!\")\n",
    "else:\n",
    "    raise ValueError(f\"FAIL: Model has {param_count} parameters, exceeds 100,000 limit!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 5: Train Model with Learning Rate Scheduler & Callbacks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "optimizer = keras.optimizers.Adam(learning_rate=1e-3)\n",
    "model.compile(\n",
    "    optimizer=optimizer,\n",
    "    loss='categorical_crossentropy',\n",
    "    metrics=['accuracy']\n",
    ")\n",
    "\n",
    "callbacks = [\n",
    "    keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=15, restore_best_weights=True, verbose=1),\n",
    "    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-5, verbose=1)\n",
    "]\n",
    "\n",
    "EPOCHS = 60\n",
    "print(\"Starting training...\")\n",
    "history = model.fit(\n",
    "    train_ds,\n",
    "    validation_data=val_ds,\n",
    "    epochs=EPOCHS,\n",
    "    class_weight=class_weight_dict,\n",
    "    callbacks=callbacks\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 6: Plot Training Curves & Evaluate Float32 Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))\n",
    "ax1.plot(history.history['accuracy'], label='Train Accuracy')\n",
    "ax1.plot(history.history['val_accuracy'], label='Val Accuracy')\n",
    "ax1.set_title('Model Accuracy')\n",
    "ax1.set_xlabel('Epoch')\n",
    "ax1.set_ylabel('Accuracy')\n",
    "ax1.legend()\n",
    "ax1.grid(True)\n",
    "\n",
    "ax2.plot(history.history['loss'], label='Train Loss')\n",
    "ax2.plot(history.history['val_loss'], label='Val Loss')\n",
    "ax2.set_title('Model Loss')\n",
    "ax2.set_xlabel('Epoch')\n",
    "ax2.set_ylabel('Loss')\n",
    "ax2.legend()\n",
    "ax2.grid(True)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "val_loss, val_acc = model.evaluate(val_ds, verbose=0)\n",
    "test_loss, test_acc = model.evaluate(test_ds, verbose=0)\n",
    "print(f\"\\n>>> Validation Accuracy (Float32): {val_acc * 100:.2f}%\")\n",
    "print(f\">>> Test Accuracy (Float32):       {test_acc * 100:.2f}%\")\n",
    "\n",
    "if val_acc >= 0.88:\n",
    "    print(\" PASS: Achieved target goal of >= 88% Validation Accuracy!\")\n",
    "else:\n",
    "    print(\" Current validation accuracy is below 88%. You can fine-tune epochs or re-run.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 7: int8 Quantization (TFLite Converter)\n",
    "\n",
    "Full integer quantization turns float32 weights and activations to 8-bit integers (`int8`).\n",
    "This dramatically reduces model size and accelerates inference on ESP32-S3."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "saved_model_dir = 'mangosteen_saved_model'\n",
    "model.save(saved_model_dir)\n",
    "\n",
    "def representative_data_gen():\n",
    "    for images, _ in train_ds.take(20):\n",
    "        for img in images:\n",
    "            input_tensor = tf.expand_dims(img, 0)\n",
    "            yield [input_tensor]\n",
    "\n",
    "converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)\n",
    "converter.optimizations = [tf.lite.Optimize.DEFAULT]\n",
    "converter.representative_dataset = representative_data_gen\n",
    "converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]\n",
    "converter.inference_input_type = tf.int8\n",
    "converter.inference_output_type = tf.int8\n",
    "\n",
    "tflite_quant_model = converter.convert()\n",
    "\n",
    "tflite_model_file = 'mangosteen_model_int8.tflite'\n",
    "with open(tflite_model_file, 'wb') as f:\n",
    "    f.write(tflite_quant_model)\n",
    "\n",
    "size_kb = len(tflite_quant_model) / 1024.0\n",
    "print(f\" int8 Quantized Model Saved: {tflite_model_file}\")\n",
    "print(f\" Model Size: {size_kb:.2f} KB (Fits easily inside ESP32-S3 Flash!)\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 8: Evaluate Quantized Model on Test Set & Benchmark Drop"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "interpreter = tf.lite.Interpreter(model_path=tflite_model_file)\n",
    "interpreter.allocate_tensors()\n",
    "\n",
    "input_details = interpreter.get_input_details()[0]\n",
    "output_details = interpreter.get_output_details()[0]\n",
    "\n",
    "input_scale, input_zero_point = input_details['quantization']\n",
    "output_scale, output_zero_point = output_details['quantization']\n",
    "\n",
    "y_true = []\n",
    "y_pred_quant = []\n",
    "\n",
    "for images, labels in test_ds:\n",
    "    for i in range(len(images)):\n",
    "        img = images[i].numpy()\n",
    "        label = np.argmax(labels[i].numpy())\n",
    "        y_true.append(label)\n",
    "        \n",
    "        # Quantize input to int8\n",
    "        quantized_input = (img / input_scale + input_zero_point).astype(np.int8)\n",
    "        quantized_input = np.expand_dims(quantized_input, axis=0)\n",
    "        \n",
    "        interpreter.set_tensor(input_details['index'], quantized_input)\n",
    "        interpreter.invoke()\n",
    "        output = interpreter.get_tensor(output_details['index'])\n",
    "        \n",
    "        pred = np.argmax(output[0])\n",
    "        y_pred_quant.append(pred)\n",
    "\n",
    "quant_acc = np.mean(np.array(y_true) == np.array(y_pred_quant))\n",
    "accuracy_drop = (test_acc - quant_acc) * 100\n",
    "\n",
    "print(\"=\" * 50)\n",
    "print(f\"Float32 Test Accuracy:        {test_acc * 100:.2f}%\")\n",
    "print(f\"int8 Quantized Test Accuracy: {quant_acc * 100:.2f}%\")\n",
    "print(f\"Accuracy Drop:                {accuracy_drop:.2f}%\")\n",
    "print(\"=\" * 50)\n",
    "\n",
    "if abs(accuracy_drop) < 2.0:\n",
    "    print(\" PASS: Accuracy drop is minimal (< 2%) as required!\")\n",
    "else:\n",
    "    print(\" Notice: Accuracy drop is slightly above 2%.\")\n",
    "\n",
    "print(\"\\n--- Classification Report (int8) ---\")\n",
    "print(classification_report(y_true, y_pred_quant, target_names=CLASSES))\n",
    "\n",
    "print(\"--- Confusion Matrix ---\")\n",
    "cm = confusion_matrix(y_true, y_pred_quant)\n",
    "print(cm)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "--- \n",
    "### Step 9: Export `model_data.h` (C Byte Array for ESP32-S3 Firmware)\n",
    "\n",
    "Generates the C header file containing the raw bytes of the int8 TFLite model."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def convert_to_c_array(bytes_data, array_name=\"g_mangosteen_model\"):\n",
    "    hex_bytes = [f\"0x{b:02x}\" for b in bytes_data]\n",
    "    lines = []\n",
    "    for i in range(0, len(hex_bytes), 12):\n",
    "        lines.append(\"  \" + \", \".join(hex_bytes[i:i+12]))\n",
    "    \n",
    "    header_content = (\n",
    "        \"// Autogenerated model header file for ESP32-S3 TFLite Micro\\n\"\n",
    "        \"#ifndef MANGOSTEEN_MODEL_DATA_H_\\n\"\n",
    "        \"#define MANGOSTEEN_MODEL_DATA_H_\\n\\n\"\n",
    "        f\"const unsigned int {array_name}_len = {len(bytes_data)};\\n\"\n",
    "        f\"alignas(16) const unsigned char {array_name}[] = {{\\n\"\n",
    "        + \",\\n\".join(lines) +\n",
    "        \"\\n};\\n\\n\"\n",
    "        \"#endif // MANGOSTEEN_MODEL_DATA_H_\\n\"\n",
    "    )\n",
    "    return header_content\n",
    "\n",
    "with open(tflite_model_file, 'rb') as f:\n",
    "    model_bytes = f.read()\n",
    "\n",
    "header_file = 'model_data.h'\n",
    "with open(header_file, 'w') as f:\n",
    "    f.write(convert_to_c_array(model_bytes, array_name=\"g_mangosteen_model\"))\n",
    "\n",
    "print(f\" Exported {header_file} successfully! (Size: {len(model_bytes)} bytes)\")\n",
    "print(\"\\nDownload this `model_data.h` file and put it into your ESP32 PlatformIO project!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open('C:/AlahiMangosteen/COE67_312_Model_Training.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
print('NOTEBOOK_CREATED_SUCCESSFULLY')
